
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.eldoradocore.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.eldoradocore.item.ZultiumOreChunkItem;
import net.mcreator.eldoradocore.item.ZultiumIngotItem;
import net.mcreator.eldoradocore.item.VibrantUnoctaniumSwordItem;
import net.mcreator.eldoradocore.item.VibrantUnoctaniumShovelItem;
import net.mcreator.eldoradocore.item.VibrantUnoctaniumPickaxeItem;
import net.mcreator.eldoradocore.item.VibrantUnoctaniumHoeItem;
import net.mcreator.eldoradocore.item.VibrantUnoctaniumAxeItem;
import net.mcreator.eldoradocore.item.VibraniumIngotItem;
import net.mcreator.eldoradocore.item.VerdoriumOreChunkItem;
import net.mcreator.eldoradocore.item.VerdoriumIngotItem;
import net.mcreator.eldoradocore.item.VeldordiumIngotItem;
import net.mcreator.eldoradocore.item.UnoctaniumOreChunkItem;
import net.mcreator.eldoradocore.item.UnoctaniumIngotItem;
import net.mcreator.eldoradocore.item.UnoctaniumDustItem;
import net.mcreator.eldoradocore.item.UltomathiumBarItem;
import net.mcreator.eldoradocore.item.RawZultiumItem;
import net.mcreator.eldoradocore.item.RawVerdoriumItem;
import net.mcreator.eldoradocore.item.RawUnoctaniumItem;
import net.mcreator.eldoradocore.item.RawPureUnoctaniumItem;
import net.mcreator.eldoradocore.item.RawObscuriteItem;
import net.mcreator.eldoradocore.item.RawKyburnItem;
import net.mcreator.eldoradocore.item.RawEldoradiumItem;
import net.mcreator.eldoradocore.item.RawAbyssaliumItem;
import net.mcreator.eldoradocore.item.PureUnoctaniumOreChunkItem;
import net.mcreator.eldoradocore.item.PureUnoctaniumIngotItem;
import net.mcreator.eldoradocore.item.PureUnoctaniumDustItem;
import net.mcreator.eldoradocore.item.ObscutaniumSwordItem;
import net.mcreator.eldoradocore.item.ObscutaniumShovelItem;
import net.mcreator.eldoradocore.item.ObscutaniumPickaxeItem;
import net.mcreator.eldoradocore.item.ObscutaniumHoeItem;
import net.mcreator.eldoradocore.item.ObscutaniumHavocSwordItem;
import net.mcreator.eldoradocore.item.ObscutaniumHavocShovelItem;
import net.mcreator.eldoradocore.item.ObscutaniumHavocPickaxeItem;
import net.mcreator.eldoradocore.item.ObscutaniumHavocIngotItem;
import net.mcreator.eldoradocore.item.ObscutaniumHavocHoeItem;
import net.mcreator.eldoradocore.item.ObscutaniumHavocAxeItem;
import net.mcreator.eldoradocore.item.ObscutaniumFluxIngotItem;
import net.mcreator.eldoradocore.item.ObscutaniumEmberIngotItem;
import net.mcreator.eldoradocore.item.ObscutaniumDreadIngotItem;
import net.mcreator.eldoradocore.item.ObscutaniumCrimsonIngotItem;
import net.mcreator.eldoradocore.item.ObscutaniumBasiliskIngotItem;
import net.mcreator.eldoradocore.item.ObscutaniumAxeItem;
import net.mcreator.eldoradocore.item.ObscutaniumAlphaIngotItem;
import net.mcreator.eldoradocore.item.ObscuriteSwordItem;
import net.mcreator.eldoradocore.item.ObscuriteShovelItem;
import net.mcreator.eldoradocore.item.ObscuritePickaxeItem;
import net.mcreator.eldoradocore.item.ObscuriteOreChunkItem;
import net.mcreator.eldoradocore.item.ObscuriteIngotItem;
import net.mcreator.eldoradocore.item.ObscuriteHoeItem;
import net.mcreator.eldoradocore.item.ObscuriteDustItem;
import net.mcreator.eldoradocore.item.ObscuriteAxeItem;
import net.mcreator.eldoradocore.item.KyburnOreChunkItem;
import net.mcreator.eldoradocore.item.KyburnIngotItem;
import net.mcreator.eldoradocore.item.EldoradoSwordItem;
import net.mcreator.eldoradocore.item.EldoradoShovelItem;
import net.mcreator.eldoradocore.item.EldoradoPickaxeItem;
import net.mcreator.eldoradocore.item.EldoradoHoeItem;
import net.mcreator.eldoradocore.item.EldoradoAxeItem;
import net.mcreator.eldoradocore.item.EldoradiumOreChunkItem;
import net.mcreator.eldoradocore.item.EldoradiumIngotItem;
import net.mcreator.eldoradocore.item.EldoradiumGemItem;
import net.mcreator.eldoradocore.item.EldoradiumDustItem;
import net.mcreator.eldoradocore.item.EldoniumIngotItem;
import net.mcreator.eldoradocore.item.AbyssaliumSwordItem;
import net.mcreator.eldoradocore.item.AbyssaliumShovelItem;
import net.mcreator.eldoradocore.item.AbyssaliumPickaxeItem;
import net.mcreator.eldoradocore.item.AbyssaliumIngotItem;
import net.mcreator.eldoradocore.item.AbyssaliumHoeItem;
import net.mcreator.eldoradocore.item.AbyssaliumAzureIngotItem;
import net.mcreator.eldoradocore.item.AbyssaliumAxeItem;
import net.mcreator.eldoradocore.EldoradoCoreMod;

public class EldoradoCoreModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, EldoradoCoreMod.MODID);
	public static final RegistryObject<Item> ELDORADIUM_GEM = REGISTRY.register("eldoradium_gem", () -> new EldoradiumGemItem());
	public static final RegistryObject<Item> ELDORADIUM_GEM_ORE = block(EldoradoCoreModBlocks.ELDORADIUM_GEM_ORE);
	public static final RegistryObject<Item> ELDORADIUM_GEM_BLOCK = block(EldoradoCoreModBlocks.ELDORADIUM_GEM_BLOCK);
	public static final RegistryObject<Item> ELDORADIUM_INGOT = REGISTRY.register("eldoradium_ingot", () -> new EldoradiumIngotItem());
	public static final RegistryObject<Item> ELDORADIUM_ORE = block(EldoradoCoreModBlocks.ELDORADIUM_ORE);
	public static final RegistryObject<Item> ELDORADIUM_BLOCK = block(EldoradoCoreModBlocks.ELDORADIUM_BLOCK);
	public static final RegistryObject<Item> RAW_ELDORADIUM = REGISTRY.register("raw_eldoradium", () -> new RawEldoradiumItem());
	public static final RegistryObject<Item> ELDORADIUM_ORE_CHUNK = REGISTRY.register("eldoradium_ore_chunk", () -> new EldoradiumOreChunkItem());
	public static final RegistryObject<Item> OBSCURITE_INGOT = REGISTRY.register("obscurite_ingot", () -> new ObscuriteIngotItem());
	public static final RegistryObject<Item> OBSCURITE_ORE = block(EldoradoCoreModBlocks.OBSCURITE_ORE);
	public static final RegistryObject<Item> OBSCURITE_BLOCK = block(EldoradoCoreModBlocks.OBSCURITE_BLOCK);
	public static final RegistryObject<Item> OBSCURITE_ORE_CHUNK = REGISTRY.register("obscurite_ore_chunk", () -> new ObscuriteOreChunkItem());
	public static final RegistryObject<Item> RAW_OBSCURITE = REGISTRY.register("raw_obscurite", () -> new RawObscuriteItem());
	public static final RegistryObject<Item> UNOCTANIUM_INGOT = REGISTRY.register("unoctanium_ingot", () -> new UnoctaniumIngotItem());
	public static final RegistryObject<Item> UNOCTANIUM_ORE = block(EldoradoCoreModBlocks.UNOCTANIUM_ORE);
	public static final RegistryObject<Item> UNOCTANIUM_BLOCK = block(EldoradoCoreModBlocks.UNOCTANIUM_BLOCK);
	public static final RegistryObject<Item> RAW_UNOCTANIUM = REGISTRY.register("raw_unoctanium", () -> new RawUnoctaniumItem());
	public static final RegistryObject<Item> UNOCTANIUM_ORE_CHUNK = REGISTRY.register("unoctanium_ore_chunk", () -> new UnoctaniumOreChunkItem());
	public static final RegistryObject<Item> UNOCTANIUM_DUST = REGISTRY.register("unoctanium_dust", () -> new UnoctaniumDustItem());
	public static final RegistryObject<Item> OBSCURITE_DUST = REGISTRY.register("obscurite_dust", () -> new ObscuriteDustItem());
	public static final RegistryObject<Item> ELDORADIUM_DUST = REGISTRY.register("eldoradium_dust", () -> new EldoradiumDustItem());
	public static final RegistryObject<Item> RAW_VERDORIUM = REGISTRY.register("raw_verdorium", () -> new RawVerdoriumItem());
	public static final RegistryObject<Item> VERDORIUM_ORE_CHUNK = REGISTRY.register("verdorium_ore_chunk", () -> new VerdoriumOreChunkItem());
	public static final RegistryObject<Item> VERDORIUM_INGOT = REGISTRY.register("verdorium_ingot", () -> new VerdoriumIngotItem());
	public static final RegistryObject<Item> VERDORIUM_ORE = block(EldoradoCoreModBlocks.VERDORIUM_ORE);
	public static final RegistryObject<Item> VERDORIUM_BLOCK = block(EldoradoCoreModBlocks.VERDORIUM_BLOCK);
	public static final RegistryObject<Item> ZULTIUM_INGOT = REGISTRY.register("zultium_ingot", () -> new ZultiumIngotItem());
	public static final RegistryObject<Item> ZULTIUM_ORE = block(EldoradoCoreModBlocks.ZULTIUM_ORE);
	public static final RegistryObject<Item> ZULTIUM_BLOCK = block(EldoradoCoreModBlocks.ZULTIUM_BLOCK);
	public static final RegistryObject<Item> ZULTIUM_ORE_CHUNK = REGISTRY.register("zultium_ore_chunk", () -> new ZultiumOreChunkItem());
	public static final RegistryObject<Item> RAW_ZULTIUM = REGISTRY.register("raw_zultium", () -> new RawZultiumItem());
	public static final RegistryObject<Item> OBSCUTANIUM_BASILISK_INGOT = REGISTRY.register("obscutanium_basilisk_ingot", () -> new ObscutaniumBasiliskIngotItem());
	public static final RegistryObject<Item> OBSCUTANIUM_ALPHA_INGOT = REGISTRY.register("obscutanium_alpha_ingot", () -> new ObscutaniumAlphaIngotItem());
	public static final RegistryObject<Item> OBSCUTANIUM_CRIMSON_INGOT = REGISTRY.register("obscutanium_crimson_ingot", () -> new ObscutaniumCrimsonIngotItem());
	public static final RegistryObject<Item> OBSCUTANIUM_DREAD_INGOT = REGISTRY.register("obscutanium_dread_ingot", () -> new ObscutaniumDreadIngotItem());
	public static final RegistryObject<Item> OBSCUTANIUM_EMBER_INGOT = REGISTRY.register("obscutanium_ember_ingot", () -> new ObscutaniumEmberIngotItem());
	public static final RegistryObject<Item> OBSCUTANIUM_FLUX_INGOT = REGISTRY.register("obscutanium_flux_ingot", () -> new ObscutaniumFluxIngotItem());
	public static final RegistryObject<Item> OBSCUTANIUM_HAVOC_INGOT = REGISTRY.register("obscutanium_havoc_ingot", () -> new ObscutaniumHavocIngotItem());
	public static final RegistryObject<Item> VIBRANIUM_INGOT = REGISTRY.register("vibranium_ingot", () -> new VibraniumIngotItem());
	public static final RegistryObject<Item> ELDONIUM_INGOT = REGISTRY.register("eldonium_ingot", () -> new EldoniumIngotItem());
	public static final RegistryObject<Item> ULTOMATHIUM_BAR = REGISTRY.register("ultomathium_bar", () -> new UltomathiumBarItem());
	public static final RegistryObject<Item> ELDORADO_SAND_STONE = block(EldoradoCoreModBlocks.ELDORADO_SAND_STONE);
	public static final RegistryObject<Item> ELDORADO_SAND = block(EldoradoCoreModBlocks.ELDORADO_SAND);
	public static final RegistryObject<Item> ABYSSALIUM_INGOT = REGISTRY.register("abyssalium_ingot", () -> new AbyssaliumIngotItem());
	public static final RegistryObject<Item> ABYSSALIUM_ORE = block(EldoradoCoreModBlocks.ABYSSALIUM_ORE);
	public static final RegistryObject<Item> ABYSSALIUM_BLOCK = block(EldoradoCoreModBlocks.ABYSSALIUM_BLOCK);
	public static final RegistryObject<Item> RAW_ABYSSALIUM = REGISTRY.register("raw_abyssalium", () -> new RawAbyssaliumItem());
	public static final RegistryObject<Item> PURE_UNOCTANIUM_INGOT = REGISTRY.register("pure_unoctanium_ingot", () -> new PureUnoctaniumIngotItem());
	public static final RegistryObject<Item> PURE_UNOCTANIUM_ORE = block(EldoradoCoreModBlocks.PURE_UNOCTANIUM_ORE);
	public static final RegistryObject<Item> PURE_UNOCTANIUM_BLOCK = block(EldoradoCoreModBlocks.PURE_UNOCTANIUM_BLOCK);
	public static final RegistryObject<Item> RAW_PURE_UNOCTANIUM = REGISTRY.register("raw_pure_unoctanium", () -> new RawPureUnoctaniumItem());
	public static final RegistryObject<Item> PURE_UNOCTANIUM_ORE_CHUNK = REGISTRY.register("pure_unoctanium_ore_chunk", () -> new PureUnoctaniumOreChunkItem());
	public static final RegistryObject<Item> PURE_UNOCTANIUM_DUST = REGISTRY.register("pure_unoctanium_dust", () -> new PureUnoctaniumDustItem());
	public static final RegistryObject<Item> KYBURN_INGOT = REGISTRY.register("kyburn_ingot", () -> new KyburnIngotItem());
	public static final RegistryObject<Item> KYBURN_ORE = block(EldoradoCoreModBlocks.KYBURN_ORE);
	public static final RegistryObject<Item> KYBURN_BLOCK = block(EldoradoCoreModBlocks.KYBURN_BLOCK);
	public static final RegistryObject<Item> RAW_KYBURN = REGISTRY.register("raw_kyburn", () -> new RawKyburnItem());
	public static final RegistryObject<Item> KYBURN_ORE_CHUNK = REGISTRY.register("kyburn_ore_chunk", () -> new KyburnOreChunkItem());
	public static final RegistryObject<Item> ELDORADO_STONE = block(EldoradoCoreModBlocks.ELDORADO_STONE);
	public static final RegistryObject<Item> ELDORADO_DEEPSLATE = block(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE);
	public static final RegistryObject<Item> ELDORADO_SANDSTONE_REFINED = block(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_REFINED);
	public static final RegistryObject<Item> ABYSSALIUM_AZURE_INGOT = REGISTRY.register("abyssalium_azure_ingot", () -> new AbyssaliumAzureIngotItem());
	public static final RegistryObject<Item> ELDORADO_COBBLESTONE = block(EldoradoCoreModBlocks.ELDORADO_COBBLESTONE);
	public static final RegistryObject<Item> ELDORADO_DEEPSLATE_COBBLESTONE = block(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_COBBLESTONE);
	public static final RegistryObject<Item> VIBRANT_UNOCTANIUM_SWORD = REGISTRY.register("vibrant_unoctanium_sword", () -> new VibrantUnoctaniumSwordItem());
	public static final RegistryObject<Item> OBSCUTANIUM_HAVOC_SWORD = REGISTRY.register("obscutanium_havoc_sword", () -> new ObscutaniumHavocSwordItem());
	public static final RegistryObject<Item> OBSCUTANIUM_HAVOC_AXE = REGISTRY.register("obscutanium_havoc_axe", () -> new ObscutaniumHavocAxeItem());
	public static final RegistryObject<Item> OBSCUTANIUM_HAVOC_PICKAXE = REGISTRY.register("obscutanium_havoc_pickaxe", () -> new ObscutaniumHavocPickaxeItem());
	public static final RegistryObject<Item> OBSCUTANIUM_HAVOC_SHOVEL = REGISTRY.register("obscutanium_havoc_shovel", () -> new ObscutaniumHavocShovelItem());
	public static final RegistryObject<Item> OBSCUTANIUM_HAVOC_HOE = REGISTRY.register("obscutanium_havoc_hoe", () -> new ObscutaniumHavocHoeItem());
	public static final RegistryObject<Item> OBSCUTANIUM_SWORD = REGISTRY.register("obscutanium_sword", () -> new ObscutaniumSwordItem());
	public static final RegistryObject<Item> OBSCUTANIUM_AXE = REGISTRY.register("obscutanium_axe", () -> new ObscutaniumAxeItem());
	public static final RegistryObject<Item> OBSCUTANIUM_PICKAXE = REGISTRY.register("obscutanium_pickaxe", () -> new ObscutaniumPickaxeItem());
	public static final RegistryObject<Item> OBSCUTANIUM_SHOVEL = REGISTRY.register("obscutanium_shovel", () -> new ObscutaniumShovelItem());
	public static final RegistryObject<Item> OBSCUTANIUM_HOE = REGISTRY.register("obscutanium_hoe", () -> new ObscutaniumHoeItem());
	public static final RegistryObject<Item> ELDORADO_SWORD = REGISTRY.register("eldorado_sword", () -> new EldoradoSwordItem());
	public static final RegistryObject<Item> ELDORADO_AXE = REGISTRY.register("eldorado_axe", () -> new EldoradoAxeItem());
	public static final RegistryObject<Item> ELDORADO_PICKAXE = REGISTRY.register("eldorado_pickaxe", () -> new EldoradoPickaxeItem());
	public static final RegistryObject<Item> ELDORADO_SHOVEL = REGISTRY.register("eldorado_shovel", () -> new EldoradoShovelItem());
	public static final RegistryObject<Item> ELDORADO_HOE = REGISTRY.register("eldorado_hoe", () -> new EldoradoHoeItem());
	public static final RegistryObject<Item> ABYSSALIUM_SWORD = REGISTRY.register("abyssalium_sword", () -> new AbyssaliumSwordItem());
	public static final RegistryObject<Item> ABYSSALIUM_AXE = REGISTRY.register("abyssalium_axe", () -> new AbyssaliumAxeItem());
	public static final RegistryObject<Item> ABYSSALIUM_PICKAXE = REGISTRY.register("abyssalium_pickaxe", () -> new AbyssaliumPickaxeItem());
	public static final RegistryObject<Item> ABYSSALIUM_SHOVEL = REGISTRY.register("abyssalium_shovel", () -> new AbyssaliumShovelItem());
	public static final RegistryObject<Item> ABYSSALIUM_HOE = REGISTRY.register("abyssalium_hoe", () -> new AbyssaliumHoeItem());
	public static final RegistryObject<Item> OBSCURITE_SWORD = REGISTRY.register("obscurite_sword", () -> new ObscuriteSwordItem());
	public static final RegistryObject<Item> OBSCURITE_AXE = REGISTRY.register("obscurite_axe", () -> new ObscuriteAxeItem());
	public static final RegistryObject<Item> OBSCURITE_PICKAXE = REGISTRY.register("obscurite_pickaxe", () -> new ObscuritePickaxeItem());
	public static final RegistryObject<Item> OBSCURITE_SHOVEL = REGISTRY.register("obscurite_shovel", () -> new ObscuriteShovelItem());
	public static final RegistryObject<Item> OBSCURITE_HOE = REGISTRY.register("obscurite_hoe", () -> new ObscuriteHoeItem());
	public static final RegistryObject<Item> VIBRANT_UNOCTANIUM_AXE = REGISTRY.register("vibrant_unoctanium_axe", () -> new VibrantUnoctaniumAxeItem());
	public static final RegistryObject<Item> VIBRANT_UNOCTANIUM_PICKAXE = REGISTRY.register("vibrant_unoctanium_pickaxe", () -> new VibrantUnoctaniumPickaxeItem());
	public static final RegistryObject<Item> VIBRANT_UNOCTANIUM_SHOVEL = REGISTRY.register("vibrant_unoctanium_shovel", () -> new VibrantUnoctaniumShovelItem());
	public static final RegistryObject<Item> VIBRANT_UNOCTANIUM_HOE = REGISTRY.register("vibrant_unoctanium_hoe", () -> new VibrantUnoctaniumHoeItem());
	public static final RegistryObject<Item> ELDORADO_DUST = block(EldoradoCoreModBlocks.ELDORADO_DUST);
	public static final RegistryObject<Item> ELDORADO_GRAVEL = block(EldoradoCoreModBlocks.ELDORADO_GRAVEL);
	public static final RegistryObject<Item> VELDORDIUM_INGOT = REGISTRY.register("veldordium_ingot", () -> new VeldordiumIngotItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
