
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.eldoradocore.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.eldoradocore.block.ZultiumOreBlock;
import net.mcreator.eldoradocore.block.ZultiumBlockBlock;
import net.mcreator.eldoradocore.block.VerdoriumOreBlock;
import net.mcreator.eldoradocore.block.VerdoriumBlockBlock;
import net.mcreator.eldoradocore.block.UnoctaniumOreBlock;
import net.mcreator.eldoradocore.block.UnoctaniumBlockBlock;
import net.mcreator.eldoradocore.block.PureUnoctaniumOreBlock;
import net.mcreator.eldoradocore.block.PureUnoctaniumBlockBlock;
import net.mcreator.eldoradocore.block.ObscuriteOreBlock;
import net.mcreator.eldoradocore.block.ObscuriteBlockBlock;
import net.mcreator.eldoradocore.block.KyburnOreBlock;
import net.mcreator.eldoradocore.block.KyburnBlockBlock;
import net.mcreator.eldoradocore.block.EldoradoWoodPlankStairBlock;
import net.mcreator.eldoradocore.block.EldoradoWoodPlankSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoWoodPlankCompressedStairBlock;
import net.mcreator.eldoradocore.block.EldoradoWoodPlankCompressedSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoWoodPlankCompressedBlock;
import net.mcreator.eldoradocore.block.EldoradoWoodPlankBlock;
import net.mcreator.eldoradocore.block.EldoradoWoodBlock;
import net.mcreator.eldoradocore.block.EldoradoSunWoodPlankStairBlock;
import net.mcreator.eldoradocore.block.EldoradoSunWoodPlankSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoSunWoodPlankBlock;
import net.mcreator.eldoradocore.block.EldoradoSunWoodCompressedStairBlock;
import net.mcreator.eldoradocore.block.EldoradoSunWoodCompressedSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoSunWoodCompressedBlock;
import net.mcreator.eldoradocore.block.EldoradoSunWoodBlock;
import net.mcreator.eldoradocore.block.EldoradoSunWoodBleachedPlankStairBlock;
import net.mcreator.eldoradocore.block.EldoradoSunWoodBleachedPlankSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoSunWoodBleachedPlankBlock;
import net.mcreator.eldoradocore.block.EldoradoStoneWallBlock;
import net.mcreator.eldoradocore.block.EldoradoStoneStairsBlock;
import net.mcreator.eldoradocore.block.EldoradoStoneSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoStoneButtonBlock;
import net.mcreator.eldoradocore.block.EldoradoStoneBrickStairBlock;
import net.mcreator.eldoradocore.block.EldoradoStoneBrickBlock;
import net.mcreator.eldoradocore.block.EldoradoStoneBlock;
import net.mcreator.eldoradocore.block.EldoradoSmoothStoneStairBlock;
import net.mcreator.eldoradocore.block.EldoradoSmoothStoneSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoSmoothStoneBlock;
import net.mcreator.eldoradocore.block.EldoradoSmoothDeepslateStairBlock;
import net.mcreator.eldoradocore.block.EldoradoSmoothDeepslateSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoSmoothDeepslateBlock;
import net.mcreator.eldoradocore.block.EldoradoSandstoneStairsBlock;
import net.mcreator.eldoradocore.block.EldoradoSandstoneRefinedWallBlock;
import net.mcreator.eldoradocore.block.EldoradoSandstoneRefinedStairsBlock;
import net.mcreator.eldoradocore.block.EldoradoSandstoneRefinedSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoSandstoneRefinedButtonBlock;
import net.mcreator.eldoradocore.block.EldoradoSandstoneRefinedBlock;
import net.mcreator.eldoradocore.block.EldoradoSandstoneBrickStairBlock;
import net.mcreator.eldoradocore.block.EldoradoSandstoneBrickSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoSandstoneBrickBlock;
import net.mcreator.eldoradocore.block.EldoradoSandStoneWallBlock;
import net.mcreator.eldoradocore.block.EldoradoSandStoneSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoSandStoneButtonBlock;
import net.mcreator.eldoradocore.block.EldoradoSandStoneBlock;
import net.mcreator.eldoradocore.block.EldoradoSandBlock;
import net.mcreator.eldoradocore.block.EldoradoMoonStoneStairBlock;
import net.mcreator.eldoradocore.block.EldoradoMoonStoneSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoMoonStoneBlock;
import net.mcreator.eldoradocore.block.EldoradoGravelBlock;
import net.mcreator.eldoradocore.block.EldoradoDustBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateWallBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateStairsBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateCobblestoneBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateCobbleWallBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateCobbleStairsBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateCobbleSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateCobbleButtonBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateButtonBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateBrickStairBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateBrickBlock;
import net.mcreator.eldoradocore.block.EldoradoDeepslateBlock;
import net.mcreator.eldoradocore.block.EldoradoCobblestoneWallBlock;
import net.mcreator.eldoradocore.block.EldoradoCobblestoneStairsBlock;
import net.mcreator.eldoradocore.block.EldoradoCobblestoneSlabBlock;
import net.mcreator.eldoradocore.block.EldoradoCobblestoneButtonBlock;
import net.mcreator.eldoradocore.block.EldoradoCobblestoneBlock;
import net.mcreator.eldoradocore.block.EldoradiumOreBlock;
import net.mcreator.eldoradocore.block.EldoradiumGemOreBlock;
import net.mcreator.eldoradocore.block.EldoradiumGemBlockBlock;
import net.mcreator.eldoradocore.block.EldoradiumBlockBlock;
import net.mcreator.eldoradocore.block.AbyssaliumOreBlock;
import net.mcreator.eldoradocore.block.AbyssaliumBlockBlock;
import net.mcreator.eldoradocore.EldoradoCoreMod;

public class EldoradoCoreModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, EldoradoCoreMod.MODID);
	public static final RegistryObject<Block> ELDORADIUM_GEM_ORE = REGISTRY.register("eldoradium_gem_ore", () -> new EldoradiumGemOreBlock());
	public static final RegistryObject<Block> ELDORADIUM_GEM_BLOCK = REGISTRY.register("eldoradium_gem_block", () -> new EldoradiumGemBlockBlock());
	public static final RegistryObject<Block> ELDORADIUM_ORE = REGISTRY.register("eldoradium_ore", () -> new EldoradiumOreBlock());
	public static final RegistryObject<Block> ELDORADIUM_BLOCK = REGISTRY.register("eldoradium_block", () -> new EldoradiumBlockBlock());
	public static final RegistryObject<Block> OBSCURITE_ORE = REGISTRY.register("obscurite_ore", () -> new ObscuriteOreBlock());
	public static final RegistryObject<Block> OBSCURITE_BLOCK = REGISTRY.register("obscurite_block", () -> new ObscuriteBlockBlock());
	public static final RegistryObject<Block> UNOCTANIUM_ORE = REGISTRY.register("unoctanium_ore", () -> new UnoctaniumOreBlock());
	public static final RegistryObject<Block> UNOCTANIUM_BLOCK = REGISTRY.register("unoctanium_block", () -> new UnoctaniumBlockBlock());
	public static final RegistryObject<Block> VERDORIUM_ORE = REGISTRY.register("verdorium_ore", () -> new VerdoriumOreBlock());
	public static final RegistryObject<Block> VERDORIUM_BLOCK = REGISTRY.register("verdorium_block", () -> new VerdoriumBlockBlock());
	public static final RegistryObject<Block> ZULTIUM_ORE = REGISTRY.register("zultium_ore", () -> new ZultiumOreBlock());
	public static final RegistryObject<Block> ZULTIUM_BLOCK = REGISTRY.register("zultium_block", () -> new ZultiumBlockBlock());
	public static final RegistryObject<Block> ELDORADO_SAND_STONE = REGISTRY.register("eldorado_sand_stone", () -> new EldoradoSandStoneBlock());
	public static final RegistryObject<Block> ELDORADO_SAND = REGISTRY.register("eldorado_sand", () -> new EldoradoSandBlock());
	public static final RegistryObject<Block> ABYSSALIUM_ORE = REGISTRY.register("abyssalium_ore", () -> new AbyssaliumOreBlock());
	public static final RegistryObject<Block> ABYSSALIUM_BLOCK = REGISTRY.register("abyssalium_block", () -> new AbyssaliumBlockBlock());
	public static final RegistryObject<Block> PURE_UNOCTANIUM_ORE = REGISTRY.register("pure_unoctanium_ore", () -> new PureUnoctaniumOreBlock());
	public static final RegistryObject<Block> PURE_UNOCTANIUM_BLOCK = REGISTRY.register("pure_unoctanium_block", () -> new PureUnoctaniumBlockBlock());
	public static final RegistryObject<Block> KYBURN_ORE = REGISTRY.register("kyburn_ore", () -> new KyburnOreBlock());
	public static final RegistryObject<Block> KYBURN_BLOCK = REGISTRY.register("kyburn_block", () -> new KyburnBlockBlock());
	public static final RegistryObject<Block> ELDORADO_STONE = REGISTRY.register("eldorado_stone", () -> new EldoradoStoneBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE = REGISTRY.register("eldorado_deepslate", () -> new EldoradoDeepslateBlock());
	public static final RegistryObject<Block> ELDORADO_SANDSTONE_REFINED = REGISTRY.register("eldorado_sandstone_refined", () -> new EldoradoSandstoneRefinedBlock());
	public static final RegistryObject<Block> ELDORADO_COBBLESTONE = REGISTRY.register("eldorado_cobblestone", () -> new EldoradoCobblestoneBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_COBBLESTONE = REGISTRY.register("eldorado_deepslate_cobblestone", () -> new EldoradoDeepslateCobblestoneBlock());
	public static final RegistryObject<Block> ELDORADO_DUST = REGISTRY.register("eldorado_dust", () -> new EldoradoDustBlock());
	public static final RegistryObject<Block> ELDORADO_GRAVEL = REGISTRY.register("eldorado_gravel", () -> new EldoradoGravelBlock());
	public static final RegistryObject<Block> ELDORADO_COBBLESTONE_STAIRS = REGISTRY.register("eldorado_cobblestone_stairs", () -> new EldoradoCobblestoneStairsBlock());
	public static final RegistryObject<Block> ELDORADO_SANDSTONE_STAIRS = REGISTRY.register("eldorado_sandstone_stairs", () -> new EldoradoSandstoneStairsBlock());
	public static final RegistryObject<Block> ELDORADO_STONE_STAIRS = REGISTRY.register("eldorado_stone_stairs", () -> new EldoradoStoneStairsBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_STAIRS = REGISTRY.register("eldorado_deepslate_stairs", () -> new EldoradoDeepslateStairsBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_COBBLE_STAIRS = REGISTRY.register("eldorado_deepslate_cobble_stairs", () -> new EldoradoDeepslateCobbleStairsBlock());
	public static final RegistryObject<Block> ELDORADO_SANDSTONE_REFINED_STAIRS = REGISTRY.register("eldorado_sandstone_refined_stairs", () -> new EldoradoSandstoneRefinedStairsBlock());
	public static final RegistryObject<Block> ELDORADO_SAND_STONE_SLAB = REGISTRY.register("eldorado_sand_stone_slab", () -> new EldoradoSandStoneSlabBlock());
	public static final RegistryObject<Block> ELDORADO_STONE_SLAB = REGISTRY.register("eldorado_stone_slab", () -> new EldoradoStoneSlabBlock());
	public static final RegistryObject<Block> ELDORADO_SANDSTONE_REFINED_SLAB = REGISTRY.register("eldorado_sandstone_refined_slab", () -> new EldoradoSandstoneRefinedSlabBlock());
	public static final RegistryObject<Block> ELDORADO_COBBLESTONE_SLAB = REGISTRY.register("eldorado_cobblestone_slab", () -> new EldoradoCobblestoneSlabBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_COBBLE_SLAB = REGISTRY.register("eldorado_deepslate_cobble_slab", () -> new EldoradoDeepslateCobbleSlabBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_SLAB = REGISTRY.register("eldorado_deepslate_slab", () -> new EldoradoDeepslateSlabBlock());
	public static final RegistryObject<Block> ELDORADO_SAND_STONE_WALL = REGISTRY.register("eldorado_sand_stone_wall", () -> new EldoradoSandStoneWallBlock());
	public static final RegistryObject<Block> ELDORADO_STONE_WALL = REGISTRY.register("eldorado_stone_wall", () -> new EldoradoStoneWallBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_WALL = REGISTRY.register("eldorado_deepslate_wall", () -> new EldoradoDeepslateWallBlock());
	public static final RegistryObject<Block> ELDORADO_SANDSTONE_REFINED_WALL = REGISTRY.register("eldorado_sandstone_refined_wall", () -> new EldoradoSandstoneRefinedWallBlock());
	public static final RegistryObject<Block> ELDORADO_COBBLESTONE_WALL = REGISTRY.register("eldorado_cobblestone_wall", () -> new EldoradoCobblestoneWallBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_COBBLE_WALL = REGISTRY.register("eldorado_deepslate_cobble_wall", () -> new EldoradoDeepslateCobbleWallBlock());
	public static final RegistryObject<Block> ELDORADO_SAND_STONE_BUTTON = REGISTRY.register("eldorado_sand_stone_button", () -> new EldoradoSandStoneButtonBlock());
	public static final RegistryObject<Block> ELDORADO_STONE_BUTTON = REGISTRY.register("eldorado_stone_button", () -> new EldoradoStoneButtonBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_BUTTON = REGISTRY.register("eldorado_deepslate_button", () -> new EldoradoDeepslateButtonBlock());
	public static final RegistryObject<Block> ELDORADO_SANDSTONE_REFINED_BUTTON = REGISTRY.register("eldorado_sandstone_refined_button", () -> new EldoradoSandstoneRefinedButtonBlock());
	public static final RegistryObject<Block> ELDORADO_COBBLESTONE_BUTTON = REGISTRY.register("eldorado_cobblestone_button", () -> new EldoradoCobblestoneButtonBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_COBBLE_BUTTON = REGISTRY.register("eldorado_deepslate_cobble_button", () -> new EldoradoDeepslateCobbleButtonBlock());
	public static final RegistryObject<Block> ELDORADO_WOOD = REGISTRY.register("eldorado_wood", () -> new EldoradoWoodBlock());
	public static final RegistryObject<Block> ELDORADO_SUN_WOOD = REGISTRY.register("eldorado_sun_wood", () -> new EldoradoSunWoodBlock());
	public static final RegistryObject<Block> ELDORADO_SMOOTH_STONE = REGISTRY.register("eldorado_smooth_stone", () -> new EldoradoSmoothStoneBlock());
	public static final RegistryObject<Block> ELDORADO_SMOOTH_DEEPSLATE = REGISTRY.register("eldorado_smooth_deepslate", () -> new EldoradoSmoothDeepslateBlock());
	public static final RegistryObject<Block> ELDORADO_MOON_STONE = REGISTRY.register("eldorado_moon_stone", () -> new EldoradoMoonStoneBlock());
	public static final RegistryObject<Block> ELDORADO_SUN_WOOD_PLANK = REGISTRY.register("eldorado_sun_wood_plank", () -> new EldoradoSunWoodPlankBlock());
	public static final RegistryObject<Block> ELDORADO_SUN_WOOD_BLEACHED_PLANK = REGISTRY.register("eldorado_sun_wood_bleached_plank", () -> new EldoradoSunWoodBleachedPlankBlock());
	public static final RegistryObject<Block> ELDORADO_SUN_WOOD_COMPRESSED = REGISTRY.register("eldorado_sun_wood_compressed", () -> new EldoradoSunWoodCompressedBlock());
	public static final RegistryObject<Block> ELDORADO_WOOD_PLANK = REGISTRY.register("eldorado_wood_plank", () -> new EldoradoWoodPlankBlock());
	public static final RegistryObject<Block> ELDORADO_WOOD_PLANK_COMPRESSED = REGISTRY.register("eldorado_wood_plank_compressed", () -> new EldoradoWoodPlankCompressedBlock());
	public static final RegistryObject<Block> ELDORADO_SANDSTONE_BRICK = REGISTRY.register("eldorado_sandstone_brick", () -> new EldoradoSandstoneBrickBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_BRICK = REGISTRY.register("eldorado_deepslate_brick", () -> new EldoradoDeepslateBrickBlock());
	public static final RegistryObject<Block> ELDORADO_STONE_BRICK = REGISTRY.register("eldorado_stone_brick", () -> new EldoradoStoneBrickBlock());
	public static final RegistryObject<Block> ELDORADO_SMOOTH_STONE_STAIR = REGISTRY.register("eldorado_smooth_stone_stair", () -> new EldoradoSmoothStoneStairBlock());
	public static final RegistryObject<Block> ELDORADO_SMOOTH_DEEPSLATE_STAIR = REGISTRY.register("eldorado_smooth_deepslate_stair", () -> new EldoradoSmoothDeepslateStairBlock());
	public static final RegistryObject<Block> ELDORADO_MOON_STONE_STAIR = REGISTRY.register("eldorado_moon_stone_stair", () -> new EldoradoMoonStoneStairBlock());
	public static final RegistryObject<Block> ELDORADO_SUN_WOOD_PLANK_STAIR = REGISTRY.register("eldorado_sun_wood_plank_stair", () -> new EldoradoSunWoodPlankStairBlock());
	public static final RegistryObject<Block> ELDORADO_SUN_WOOD_BLEACHED_PLANK_STAIR = REGISTRY.register("eldorado_sun_wood_bleached_plank_stair", () -> new EldoradoSunWoodBleachedPlankStairBlock());
	public static final RegistryObject<Block> ELDORADO_SUN_WOOD_COMPRESSED_STAIR = REGISTRY.register("eldorado_sun_wood_compressed_stair", () -> new EldoradoSunWoodCompressedStairBlock());
	public static final RegistryObject<Block> ELDORADO_WOOD_PLANK_STAIR = REGISTRY.register("eldorado_wood_plank_stair", () -> new EldoradoWoodPlankStairBlock());
	public static final RegistryObject<Block> ELDORADO_WOOD_PLANK_COMPRESSED_STAIR = REGISTRY.register("eldorado_wood_plank_compressed_stair", () -> new EldoradoWoodPlankCompressedStairBlock());
	public static final RegistryObject<Block> ELDORADO_SANDSTONE_BRICK_STAIR = REGISTRY.register("eldorado_sandstone_brick_stair", () -> new EldoradoSandstoneBrickStairBlock());
	public static final RegistryObject<Block> ELDORADO_DEEPSLATE_BRICK_STAIR = REGISTRY.register("eldorado_deepslate_brick_stair", () -> new EldoradoDeepslateBrickStairBlock());
	public static final RegistryObject<Block> ELDORADO_STONE_BRICK_STAIR = REGISTRY.register("eldorado_stone_brick_stair", () -> new EldoradoStoneBrickStairBlock());
	public static final RegistryObject<Block> ELDORADO_SMOOTH_STONE_SLAB = REGISTRY.register("eldorado_smooth_stone_slab", () -> new EldoradoSmoothStoneSlabBlock());
	public static final RegistryObject<Block> ELDORADO_SMOOTH_DEEPSLATE_SLAB = REGISTRY.register("eldorado_smooth_deepslate_slab", () -> new EldoradoSmoothDeepslateSlabBlock());
	public static final RegistryObject<Block> ELDORADO_MOON_STONE_SLAB = REGISTRY.register("eldorado_moon_stone_slab", () -> new EldoradoMoonStoneSlabBlock());
	public static final RegistryObject<Block> ELDORADO_SUN_WOOD_PLANK_SLAB = REGISTRY.register("eldorado_sun_wood_plank_slab", () -> new EldoradoSunWoodPlankSlabBlock());
	public static final RegistryObject<Block> ELDORADO_SUN_WOOD_BLEACHED_PLANK_SLAB = REGISTRY.register("eldorado_sun_wood_bleached_plank_slab", () -> new EldoradoSunWoodBleachedPlankSlabBlock());
	public static final RegistryObject<Block> ELDORADO_SUN_WOOD_COMPRESSED_SLAB = REGISTRY.register("eldorado_sun_wood_compressed_slab", () -> new EldoradoSunWoodCompressedSlabBlock());
	public static final RegistryObject<Block> ELDORADO_WOOD_PLANK_SLAB = REGISTRY.register("eldorado_wood_plank_slab", () -> new EldoradoWoodPlankSlabBlock());
	public static final RegistryObject<Block> ELDORADO_WOOD_PLANK_COMPRESSED_SLAB = REGISTRY.register("eldorado_wood_plank_compressed_slab", () -> new EldoradoWoodPlankCompressedSlabBlock());
	public static final RegistryObject<Block> ELDORADO_SANDSTONE_BRICK_SLAB = REGISTRY.register("eldorado_sandstone_brick_slab", () -> new EldoradoSandstoneBrickSlabBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
