
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.eldoradocore.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.eldoradocore.EldoradoCoreMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class EldoradoCoreModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, EldoradoCoreMod.MODID);
	public static final RegistryObject<CreativeModeTab> ELDORADO_CORE = REGISTRY.register("eldorado_core",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.eldorado_core.eldorado_core")).icon(() -> new ItemStack(EldoradoCoreModBlocks.ELDORADIUM_BLOCK.get())).displayItems((parameters, tabData) -> {
				tabData.accept(EldoradoCoreModBlocks.ELDORADIUM_GEM_BLOCK.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADIUM_GEM_ORE.get().asItem());
				tabData.accept(EldoradoCoreModItems.ELDORADIUM_GEM.get());
				tabData.accept(EldoradoCoreModBlocks.ELDORADIUM_ORE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADIUM_BLOCK.get().asItem());
				tabData.accept(EldoradoCoreModItems.ELDORADIUM_INGOT.get());
				tabData.accept(EldoradoCoreModItems.RAW_ELDORADIUM.get());
				tabData.accept(EldoradoCoreModItems.ELDORADIUM_ORE_CHUNK.get());
				tabData.accept(EldoradoCoreModBlocks.OBSCURITE_ORE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.OBSCURITE_BLOCK.get().asItem());
				tabData.accept(EldoradoCoreModItems.OBSCURITE_INGOT.get());
				tabData.accept(EldoradoCoreModItems.OBSCURITE_ORE_CHUNK.get());
				tabData.accept(EldoradoCoreModItems.RAW_OBSCURITE.get());
				tabData.accept(EldoradoCoreModBlocks.UNOCTANIUM_ORE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.UNOCTANIUM_BLOCK.get().asItem());
				tabData.accept(EldoradoCoreModItems.UNOCTANIUM_INGOT.get());
				tabData.accept(EldoradoCoreModItems.RAW_UNOCTANIUM.get());
				tabData.accept(EldoradoCoreModItems.UNOCTANIUM_ORE_CHUNK.get());
				tabData.accept(EldoradoCoreModItems.UNOCTANIUM_DUST.get());
				tabData.accept(EldoradoCoreModItems.OBSCURITE_DUST.get());
				tabData.accept(EldoradoCoreModItems.ELDORADIUM_DUST.get());
				tabData.accept(EldoradoCoreModItems.RAW_VERDORIUM.get());
				tabData.accept(EldoradoCoreModItems.VERDORIUM_ORE_CHUNK.get());
				tabData.accept(EldoradoCoreModBlocks.VERDORIUM_ORE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.VERDORIUM_BLOCK.get().asItem());
				tabData.accept(EldoradoCoreModItems.VERDORIUM_INGOT.get());
				tabData.accept(EldoradoCoreModBlocks.ZULTIUM_ORE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ZULTIUM_BLOCK.get().asItem());
				tabData.accept(EldoradoCoreModItems.ZULTIUM_INGOT.get());
				tabData.accept(EldoradoCoreModItems.ZULTIUM_ORE_CHUNK.get());
				tabData.accept(EldoradoCoreModItems.RAW_ZULTIUM.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_BASILISK_INGOT.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_ALPHA_INGOT.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_CRIMSON_INGOT.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_DREAD_INGOT.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_EMBER_INGOT.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_FLUX_INGOT.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_HAVOC_INGOT.get());
				tabData.accept(EldoradoCoreModItems.VIBRANIUM_INGOT.get());
				tabData.accept(EldoradoCoreModItems.ELDONIUM_INGOT.get());
				tabData.accept(EldoradoCoreModItems.ULTOMATHIUM_BAR.get());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SAND_STONE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SAND.get().asItem());
				tabData.accept(EldoradoCoreModItems.ABYSSALIUM_INGOT.get());
				tabData.accept(EldoradoCoreModBlocks.ABYSSALIUM_ORE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ABYSSALIUM_BLOCK.get().asItem());
				tabData.accept(EldoradoCoreModItems.RAW_ABYSSALIUM.get());
				tabData.accept(EldoradoCoreModItems.PURE_UNOCTANIUM_INGOT.get());
				tabData.accept(EldoradoCoreModBlocks.PURE_UNOCTANIUM_ORE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.PURE_UNOCTANIUM_BLOCK.get().asItem());
				tabData.accept(EldoradoCoreModItems.RAW_PURE_UNOCTANIUM.get());
				tabData.accept(EldoradoCoreModItems.PURE_UNOCTANIUM_ORE_CHUNK.get());
				tabData.accept(EldoradoCoreModItems.PURE_UNOCTANIUM_DUST.get());
				tabData.accept(EldoradoCoreModItems.KYBURN_INGOT.get());
				tabData.accept(EldoradoCoreModBlocks.KYBURN_ORE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.KYBURN_BLOCK.get().asItem());
				tabData.accept(EldoradoCoreModItems.RAW_KYBURN.get());
				tabData.accept(EldoradoCoreModItems.KYBURN_ORE_CHUNK.get());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_REFINED.get().asItem());
				tabData.accept(EldoradoCoreModItems.ABYSSALIUM_AZURE_INGOT.get());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_COBBLESTONE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_COBBLESTONE.get().asItem());
				tabData.accept(EldoradoCoreModItems.VIBRANT_UNOCTANIUM_SWORD.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_HAVOC_SWORD.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_HAVOC_AXE.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_HAVOC_PICKAXE.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_HAVOC_SHOVEL.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_HAVOC_HOE.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_SWORD.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_AXE.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_PICKAXE.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_SHOVEL.get());
				tabData.accept(EldoradoCoreModItems.OBSCUTANIUM_HOE.get());
				tabData.accept(EldoradoCoreModItems.ELDORADO_SWORD.get());
				tabData.accept(EldoradoCoreModItems.ELDORADO_AXE.get());
				tabData.accept(EldoradoCoreModItems.ELDORADO_PICKAXE.get());
				tabData.accept(EldoradoCoreModItems.ELDORADO_SHOVEL.get());
				tabData.accept(EldoradoCoreModItems.ELDORADO_HOE.get());
				tabData.accept(EldoradoCoreModItems.ABYSSALIUM_SWORD.get());
				tabData.accept(EldoradoCoreModItems.ABYSSALIUM_AXE.get());
				tabData.accept(EldoradoCoreModItems.ABYSSALIUM_PICKAXE.get());
				tabData.accept(EldoradoCoreModItems.ABYSSALIUM_SHOVEL.get());
				tabData.accept(EldoradoCoreModItems.ABYSSALIUM_HOE.get());
				tabData.accept(EldoradoCoreModItems.OBSCURITE_SWORD.get());
				tabData.accept(EldoradoCoreModItems.OBSCURITE_AXE.get());
				tabData.accept(EldoradoCoreModItems.OBSCURITE_PICKAXE.get());
				tabData.accept(EldoradoCoreModItems.OBSCURITE_SHOVEL.get());
				tabData.accept(EldoradoCoreModItems.OBSCURITE_HOE.get());
				tabData.accept(EldoradoCoreModItems.VIBRANT_UNOCTANIUM_AXE.get());
				tabData.accept(EldoradoCoreModItems.VIBRANT_UNOCTANIUM_PICKAXE.get());
				tabData.accept(EldoradoCoreModItems.VIBRANT_UNOCTANIUM_SHOVEL.get());
				tabData.accept(EldoradoCoreModItems.VIBRANT_UNOCTANIUM_HOE.get());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DUST.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_GRAVEL.get().asItem());
				tabData.accept(EldoradoCoreModItems.VELDORDIUM_INGOT.get());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_COBBLESTONE_STAIRS.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_STAIRS.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_STAIRS.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_STAIRS.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_COBBLE_STAIRS.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_REFINED_STAIRS.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SAND_STONE_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_REFINED_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_COBBLESTONE_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_COBBLE_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SAND_STONE_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_REFINED_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_COBBLESTONE_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_COBBLE_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SAND_STONE_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_REFINED_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_COBBLESTONE_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_COBBLE_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_STONE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_DEEPSLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_MOON_STONE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_PLANK.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_BLEACHED_PLANK.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_PLANK.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_PLANK_COMPRESSED.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_BRICK.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_BRICK.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_BRICK.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_STONE_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_DEEPSLATE_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_MOON_STONE_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_BRICK_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_BRICK_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_BRICK_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_STONE_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_DEEPSLATE_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_MOON_STONE_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_BRICK_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_BRICK_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_BRICK_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_COMPRESSED_PLANK.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_BLEACHED_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_COMPRESSED_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_COMPRESSED_STAIR.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_BLEACHED_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_COMPRESSED_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_COMPRESSED_SLAB.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_FENCE.get().asItem());
				tabData.accept(EldoradoCoreModItems.ELDORADO_SUN_WOOD_STICK.get());
				tabData.accept(EldoradoCoreModItems.ELDORADO_SUN_WOOD_BLEACHED_STICK.get());
				tabData.accept(EldoradoCoreModItems.ELDORADO_WOOD_STICK.get());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_BLEACHED_FENCE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_COMPRESSED_FENCE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_FENCE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_COMPRESSED_FENCE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_STONE_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_DEEPSLATE_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_MOON_STONE_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_BRICK_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_BRICK_WALL.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_BRICK_WALL.get().asItem());
				tabData.accept(EldoradoCoreModItems.SUNFIRE_AXE.get());
				tabData.accept(EldoradoCoreModItems.SUNFIRE_PICKAXE.get());
				tabData.accept(EldoradoCoreModItems.ABYSSALIUM_ORE_CHUNK.get());
				tabData.accept(EldoradoCoreModItems.RAW_SUNFIRE.get());
				tabData.accept(EldoradoCoreModItems.SUNFIRE_ORE_CHUNK.get());
				tabData.accept(EldoradoCoreModItems.SUNFIRE_DUST.get());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_STONE_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_DEEPSLATE_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_MOON_STONE_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_BLEACHED_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_COMPRESSED_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_COMPRESSED_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_BRICK_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_BRICK_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_BRICK_BUTTON.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SAND_STONE_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_REFINED_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_COBBLESTONE_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_COBBLE_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_STONE_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SMOOTH_DEEPSLATE_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_MOON_STONE_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_BLEACHED_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SUN_WOOD_COMPRESSED_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_WOOD_COMPRESSED_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_SANDSTONE_BRICK_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_DEEPSLATE_BRICK_PRESSURE_PLATE.get().asItem());
				tabData.accept(EldoradoCoreModBlocks.ELDORADO_STONE_BRICK_PRESSURE_PLATE.get().asItem());
			}).withSearchBar().build());

	@SubscribeEvent
	public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
		if (tabData.getTabKey() == CreativeModeTabs.BUILDING_BLOCKS) {
			tabData.accept(EldoradoCoreModBlocks.SUNFIRE_ORE.get().asItem());
			tabData.accept(EldoradoCoreModBlocks.SUNFIRE_BLOCK.get().asItem());
			tabData.accept(EldoradoCoreModBlocks.ELDORADO_RUBY_ORE.get().asItem());
			tabData.accept(EldoradoCoreModBlocks.ELDORADO_RUBY_BLOCK.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.INGREDIENTS) {
			tabData.accept(EldoradoCoreModItems.SUNFIRE_INGOT.get());
			tabData.accept(EldoradoCoreModItems.ELDORADO_RUBY.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.TOOLS_AND_UTILITIES) {
			tabData.accept(EldoradoCoreModItems.SUNFIRE_HOE.get());
			tabData.accept(EldoradoCoreModItems.SUNFIRE_SHOVEL.get());
			tabData.accept(EldoradoCoreModItems.SUNFIRE_SWORD.get());
		}
	}
}
